// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

#include <gnome.h>

const gchar *__prefix = "__gtksharp_";

#define HAS_PREFIX(a) (*((guint64 *)(a)) == *((guint64 *) __prefix))

static GObjectClass *
get_threshold_class (GObject *obj)
{
	GType gtype = G_TYPE_FROM_INSTANCE (obj);
	while (HAS_PREFIX (g_type_name (gtype)))
		gtype = g_type_parent (gtype);
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL) klass = g_type_class_ref (gtype);
	return klass;
}

guint gnomesharp_gnome_moduleinfo_get_name_offset (void);

guint
gnomesharp_gnome_moduleinfo_get_name_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeModuleInfo, name);
}

guint gnomesharp_gnome_moduleinfo_get_description_offset (void);

guint
gnomesharp_gnome_moduleinfo_get_description_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeModuleInfo, description);
}

guint gnomesharp_gnome_moduleinfo_get_version_offset (void);

guint
gnomesharp_gnome_moduleinfo_get_version_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeModuleInfo, version);
}

guint gnomesharp_gnome_canvas_get_pixels_per_unit_offset (void);

guint
gnomesharp_gnome_canvas_get_pixels_per_unit_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeCanvas, pixels_per_unit);
}

void gnomesharp_canvas_override_render_background (GType gtype, gpointer cb);

void
gnomesharp_canvas_override_render_background (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeCanvasClass *)klass)->render_background = cb;
}

void gnomesharp_canvas_base_render_background (GnomeCanvas* canvas, GnomeCanvasBuf* buf);

void
gnomesharp_canvas_base_render_background (GnomeCanvas* canvas, GnomeCanvasBuf* buf)
{
	GnomeCanvasClass *klass = (GnomeCanvasClass *) get_threshold_class (G_OBJECT (canvas));
	if (klass->render_background)
		(* klass->render_background) (canvas, buf);
}
void gnomesharp_canvas_override_draw_background (GType gtype, gpointer cb);

void
gnomesharp_canvas_override_draw_background (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeCanvasClass *)klass)->draw_background = cb;
}

void gnomesharp_canvas_base_draw_background (GnomeCanvas* canvas, GdkDrawable* drawable, int x, int y, int width, int height);

void
gnomesharp_canvas_base_draw_background (GnomeCanvas* canvas, GdkDrawable* drawable, int x, int y, int width, int height)
{
	GnomeCanvasClass *klass = (GnomeCanvasClass *) get_threshold_class (G_OBJECT (canvas));
	if (klass->draw_background)
		(* klass->draw_background) (canvas, drawable, x, y, width, height);
}
guint gnomesharp_gnome_canvasitem_get_canvas_offset (void);

guint
gnomesharp_gnome_canvasitem_get_canvas_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeCanvasItem, canvas);
}

void gnomesharp_canvasitem_override_event (GType gtype, gpointer cb);

void
gnomesharp_canvasitem_override_event (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeCanvasItemClass *)klass)->event = cb;
}

gboolean gnomesharp_canvasitem_base_event (GnomeCanvasItem* item, GdkEvent* evnt);

gboolean
gnomesharp_canvasitem_base_event (GnomeCanvasItem* item, GdkEvent* evnt)
{
	GnomeCanvasItemClass *klass = (GnomeCanvasItemClass *) get_threshold_class (G_OBJECT (item));
	if (klass->event)
		return (* klass->event) (item, evnt);
	return FALSE;
}
gboolean gnomesharp_gnome_canvasbuf_get_is_bg (GnomeCanvasBuf *canvasbuf);
void gnomesharp_gnome_canvasbuf_set_is_bg (GnomeCanvasBuf *canvasbuf, gboolean value);

gboolean
gnomesharp_gnome_canvasbuf_get_is_bg (GnomeCanvasBuf *canvasbuf)
{
	return (gboolean)canvasbuf->is_bg;
}

void
gnomesharp_gnome_canvasbuf_set_is_bg (GnomeCanvasBuf *canvasbuf, gboolean value)
{
	canvasbuf->is_bg = (gboolean)value;
}

gboolean gnomesharp_gnome_canvasbuf_get_is_buf (GnomeCanvasBuf *canvasbuf);
void gnomesharp_gnome_canvasbuf_set_is_buf (GnomeCanvasBuf *canvasbuf, gboolean value);

gboolean
gnomesharp_gnome_canvasbuf_get_is_buf (GnomeCanvasBuf *canvasbuf)
{
	return (gboolean)canvasbuf->is_buf;
}

void
gnomesharp_gnome_canvasbuf_set_is_buf (GnomeCanvasBuf *canvasbuf, gboolean value)
{
	canvasbuf->is_buf = (gboolean)value;
}

guint gnomesharp_gnome_app_get_name_offset (void);

guint
gnomesharp_gnome_app_get_name_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeApp, name);
}

guint gnomesharp_gnome_app_get_prefix_offset (void);

guint
gnomesharp_gnome_app_get_prefix_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeApp, prefix);
}

guint gnomesharp_gnome_app_get_accel_group_offset (void);

guint
gnomesharp_gnome_app_get_accel_group_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeApp, accel_group);
}

guint gnomesharp_gnome_app_get_menubar_offset (void);

guint
gnomesharp_gnome_app_get_menubar_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeApp, menubar);
}

guint gnomesharp_gnome_app_get_contents_offset (void);

guint
gnomesharp_gnome_app_get_contents_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeApp, contents);
}

guint gnomesharp_gnome_app_get_statusbar_offset (void);

guint
gnomesharp_gnome_app_get_statusbar_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeApp, statusbar);
}

void gnomesharp_appbar_override_user_response (GType gtype, gpointer cb);

void
gnomesharp_appbar_override_user_response (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeAppBarClass *)klass)->user_response = cb;
}

void gnomesharp_appbar_base_user_response (GnomeAppBar* ab);

void
gnomesharp_appbar_base_user_response (GnomeAppBar* ab)
{
	GnomeAppBarClass *klass = (GnomeAppBarClass *) get_threshold_class (G_OBJECT (ab));
	if (klass->user_response)
		(* klass->user_response) (ab);
}
void gnomesharp_appbar_override_clear_prompt (GType gtype, gpointer cb);

void
gnomesharp_appbar_override_clear_prompt (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeAppBarClass *)klass)->clear_prompt = cb;
}

void gnomesharp_appbar_base_clear_prompt (GnomeAppBar* ab);

void
gnomesharp_appbar_base_clear_prompt (GnomeAppBar* ab)
{
	GnomeAppBarClass *klass = (GnomeAppBarClass *) get_threshold_class (G_OBJECT (ab));
	if (klass->clear_prompt)
		(* klass->clear_prompt) (ab);
}
void gnomesharp_client_override_connect (GType gtype, gpointer cb);

void
gnomesharp_client_override_connect (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeClientClass *)klass)->connect = cb;
}

void gnomesharp_client_base_connect (GnomeClient* client, gboolean restarted);

void
gnomesharp_client_base_connect (GnomeClient* client, gboolean restarted)
{
	GnomeClientClass *klass = (GnomeClientClass *) get_threshold_class (G_OBJECT (client));
	if (klass->connect)
		(* klass->connect) (client, restarted);
}
void gnomesharp_client_override_save_complete (GType gtype, gpointer cb);

void
gnomesharp_client_override_save_complete (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeClientClass *)klass)->save_complete = cb;
}

void gnomesharp_client_base_save_complete (GnomeClient* client);

void
gnomesharp_client_base_save_complete (GnomeClient* client)
{
	GnomeClientClass *klass = (GnomeClientClass *) get_threshold_class (G_OBJECT (client));
	if (klass->save_complete)
		(* klass->save_complete) (client);
}
void gnomesharp_client_override_disconnect (GType gtype, gpointer cb);

void
gnomesharp_client_override_disconnect (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeClientClass *)klass)->disconnect = cb;
}

void gnomesharp_client_base_disconnect (GnomeClient* client);

void
gnomesharp_client_base_disconnect (GnomeClient* client)
{
	GnomeClientClass *klass = (GnomeClientClass *) get_threshold_class (G_OBJECT (client));
	if (klass->disconnect)
		(* klass->disconnect) (client);
}
void gnomesharp_client_override_save_yourself (GType gtype, gpointer cb);

void
gnomesharp_client_override_save_yourself (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeClientClass *)klass)->save_yourself = cb;
}

gboolean gnomesharp_client_base_save_yourself (GnomeClient* client, gint phase, GnomeSaveStyle save_style, gboolean shutdown, GnomeInteractStyle interact_style, gboolean fast);

gboolean
gnomesharp_client_base_save_yourself (GnomeClient* client, gint phase, GnomeSaveStyle save_style, gboolean shutdown, GnomeInteractStyle interact_style, gboolean fast)
{
	GnomeClientClass *klass = (GnomeClientClass *) get_threshold_class (G_OBJECT (client));
	if (klass->save_yourself)
		return (* klass->save_yourself) (client, phase, save_style, shutdown, interact_style, fast);
	return FALSE;
}
void gnomesharp_client_override_die (GType gtype, gpointer cb);

void
gnomesharp_client_override_die (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeClientClass *)klass)->die = cb;
}

void gnomesharp_client_base_die (GnomeClient* client);

void
gnomesharp_client_base_die (GnomeClient* client)
{
	GnomeClientClass *klass = (GnomeClientClass *) get_threshold_class (G_OBJECT (client));
	if (klass->die)
		(* klass->die) (client);
}
void gnomesharp_client_override_shutdown_cancelled (GType gtype, gpointer cb);

void
gnomesharp_client_override_shutdown_cancelled (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeClientClass *)klass)->shutdown_cancelled = cb;
}

void gnomesharp_client_base_shutdown_cancelled (GnomeClient* client);

void
gnomesharp_client_base_shutdown_cancelled (GnomeClient* client)
{
	GnomeClientClass *klass = (GnomeClientClass *) get_threshold_class (G_OBJECT (client));
	if (klass->shutdown_cancelled)
		(* klass->shutdown_cancelled) (client);
}
void gnomesharp_colorpicker_override_color_set (GType gtype, gpointer cb);

void
gnomesharp_colorpicker_override_color_set (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeColorPickerClass *)klass)->color_set = cb;
}

void gnomesharp_colorpicker_base_color_set (GnomeColorPicker* cp, guint r, guint g, guint b, guint a);

void
gnomesharp_colorpicker_base_color_set (GnomeColorPicker* cp, guint r, guint g, guint b, guint a)
{
	GnomeColorPickerClass *klass = (GnomeColorPickerClass *) get_threshold_class (G_OBJECT (cp));
	if (klass->color_set)
		(* klass->color_set) (cp, r, g, b, a);
}
void gnomesharp_dateedit_override_date_changed (GType gtype, gpointer cb);

void
gnomesharp_dateedit_override_date_changed (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeDateEditClass *)klass)->date_changed = cb;
}

void gnomesharp_dateedit_base_date_changed (GnomeDateEdit* gde);

void
gnomesharp_dateedit_base_date_changed (GnomeDateEdit* gde)
{
	GnomeDateEditClass *klass = (GnomeDateEditClass *) get_threshold_class (G_OBJECT (gde));
	if (klass->date_changed)
		(* klass->date_changed) (gde);
}
void gnomesharp_dateedit_override_time_changed (GType gtype, gpointer cb);

void
gnomesharp_dateedit_override_time_changed (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeDateEditClass *)klass)->time_changed = cb;
}

void gnomesharp_dateedit_base_time_changed (GnomeDateEdit* gde);

void
gnomesharp_dateedit_base_time_changed (GnomeDateEdit* gde)
{
	GnomeDateEditClass *klass = (GnomeDateEditClass *) get_threshold_class (G_OBJECT (gde));
	if (klass->time_changed)
		(* klass->time_changed) (gde);
}
guint gnomesharp_gnome_druid_get_finish_offset (void);

guint
gnomesharp_gnome_druid_get_finish_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeDruid, finish);
}

guint gnomesharp_gnome_druid_get_next_offset (void);

guint
gnomesharp_gnome_druid_get_next_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeDruid, next);
}

guint gnomesharp_gnome_druid_get_help_offset (void);

guint
gnomesharp_gnome_druid_get_help_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeDruid, help);
}

guint gnomesharp_gnome_druid_get_back_offset (void);

guint
gnomesharp_gnome_druid_get_back_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeDruid, back);
}

guint gnomesharp_gnome_druid_get_cancel_offset (void);

guint
gnomesharp_gnome_druid_get_cancel_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeDruid, cancel);
}

void gnomesharp_druid_override_cancel (GType gtype, gpointer cb);

void
gnomesharp_druid_override_cancel (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeDruidClass *)klass)->cancel = cb;
}

void gnomesharp_druid_base_cancel (GnomeDruid* druid);

void
gnomesharp_druid_base_cancel (GnomeDruid* druid)
{
	GnomeDruidClass *klass = (GnomeDruidClass *) get_threshold_class (G_OBJECT (druid));
	if (klass->cancel)
		(* klass->cancel) (druid);
}
void gnomesharp_druid_override_help (GType gtype, gpointer cb);

void
gnomesharp_druid_override_help (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeDruidClass *)klass)->help = cb;
}

void gnomesharp_druid_base_help (GnomeDruid* druid);

void
gnomesharp_druid_base_help (GnomeDruid* druid)
{
	GnomeDruidClass *klass = (GnomeDruidClass *) get_threshold_class (G_OBJECT (druid));
	if (klass->help)
		(* klass->help) (druid);
}
void gnomesharp_druidpage_override_prepare (GType gtype, gpointer cb);

void
gnomesharp_druidpage_override_prepare (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeDruidPageClass *)klass)->prepare = cb;
}

void gnomesharp_druidpage_base_prepare (GnomeDruidPage* druid_page, GtkWidget* druid);

void
gnomesharp_druidpage_base_prepare (GnomeDruidPage* druid_page, GtkWidget* druid)
{
	GnomeDruidPageClass *klass = (GnomeDruidPageClass *) get_threshold_class (G_OBJECT (druid_page));
	if (klass->prepare)
		(* klass->prepare) (druid_page, druid);
}
void gnomesharp_druidpage_override_next (GType gtype, gpointer cb);

void
gnomesharp_druidpage_override_next (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeDruidPageClass *)klass)->next = cb;
}

gboolean gnomesharp_druidpage_base_next (GnomeDruidPage* druid_page, GtkWidget* druid);

gboolean
gnomesharp_druidpage_base_next (GnomeDruidPage* druid_page, GtkWidget* druid)
{
	GnomeDruidPageClass *klass = (GnomeDruidPageClass *) get_threshold_class (G_OBJECT (druid_page));
	if (klass->next)
		return (* klass->next) (druid_page, druid);
	return FALSE;
}
void gnomesharp_druidpage_override_finish (GType gtype, gpointer cb);

void
gnomesharp_druidpage_override_finish (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeDruidPageClass *)klass)->finish = cb;
}

void gnomesharp_druidpage_base_finish (GnomeDruidPage* druid_page, GtkWidget* druid);

void
gnomesharp_druidpage_base_finish (GnomeDruidPage* druid_page, GtkWidget* druid)
{
	GnomeDruidPageClass *klass = (GnomeDruidPageClass *) get_threshold_class (G_OBJECT (druid_page));
	if (klass->finish)
		(* klass->finish) (druid_page, druid);
}
void gnomesharp_druidpage_override_back (GType gtype, gpointer cb);

void
gnomesharp_druidpage_override_back (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeDruidPageClass *)klass)->back = cb;
}

gboolean gnomesharp_druidpage_base_back (GnomeDruidPage* druid_page, GtkWidget* druid);

gboolean
gnomesharp_druidpage_base_back (GnomeDruidPage* druid_page, GtkWidget* druid)
{
	GnomeDruidPageClass *klass = (GnomeDruidPageClass *) get_threshold_class (G_OBJECT (druid_page));
	if (klass->back)
		return (* klass->back) (druid_page, druid);
	return FALSE;
}
void gnomesharp_druidpage_override_cancel (GType gtype, gpointer cb);

void
gnomesharp_druidpage_override_cancel (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeDruidPageClass *)klass)->cancel = cb;
}

gboolean gnomesharp_druidpage_base_cancel (GnomeDruidPage* druid_page, GtkWidget* druid);

gboolean
gnomesharp_druidpage_base_cancel (GnomeDruidPage* druid_page, GtkWidget* druid)
{
	GnomeDruidPageClass *klass = (GnomeDruidPageClass *) get_threshold_class (G_OBJECT (druid_page));
	if (klass->cancel)
		return (* klass->cancel) (druid_page, druid);
	return FALSE;
}
guint gnomesharp_gnome_druidpageedge_get_top_watermark_image_offset (void);

guint
gnomesharp_gnome_druidpageedge_get_top_watermark_image_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeDruidPageEdge, top_watermark_image);
}

guint gnomesharp_gnome_druidpageedge_get_title_offset (void);

guint
gnomesharp_gnome_druidpageedge_get_title_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeDruidPageEdge, title);
}

guint gnomesharp_gnome_druidpageedge_get_textbox_color_offset (void);

guint
gnomesharp_gnome_druidpageedge_get_textbox_color_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeDruidPageEdge, textbox_color);
}

guint gnomesharp_gnome_druidpageedge_get_watermark_image_offset (void);

guint
gnomesharp_gnome_druidpageedge_get_watermark_image_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeDruidPageEdge, watermark_image);
}

guint gnomesharp_gnome_druidpageedge_get_logo_background_color_offset (void);

guint
gnomesharp_gnome_druidpageedge_get_logo_background_color_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeDruidPageEdge, logo_background_color);
}

guint gnomesharp_gnome_druidpageedge_get_text_offset (void);

guint
gnomesharp_gnome_druidpageedge_get_text_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeDruidPageEdge, text);
}

guint gnomesharp_gnome_druidpageedge_get_title_color_offset (void);

guint
gnomesharp_gnome_druidpageedge_get_title_color_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeDruidPageEdge, title_color);
}

guint gnomesharp_gnome_druidpageedge_get_logo_image_offset (void);

guint
gnomesharp_gnome_druidpageedge_get_logo_image_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeDruidPageEdge, logo_image);
}

guint gnomesharp_gnome_druidpageedge_get_text_color_offset (void);

guint
gnomesharp_gnome_druidpageedge_get_text_color_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeDruidPageEdge, text_color);
}

guint gnomesharp_gnome_druidpageedge_get_position (GnomeDruidPageEdge *druidpageedge);

guint
gnomesharp_gnome_druidpageedge_get_position (GnomeDruidPageEdge *druidpageedge)
{
	return (guint)druidpageedge->position;
}

guint gnomesharp_gnome_druidpageedge_get_background_color_offset (void);

guint
gnomesharp_gnome_druidpageedge_get_background_color_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeDruidPageEdge, background_color);
}

guint gnomesharp_gnome_druidpagestandard_get_contents_background_offset (void);

guint
gnomesharp_gnome_druidpagestandard_get_contents_background_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeDruidPageStandard, contents_background);
}

guint gnomesharp_gnome_druidpagestandard_get_vbox_offset (void);

guint
gnomesharp_gnome_druidpagestandard_get_vbox_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeDruidPageStandard, vbox);
}

guint gnomesharp_gnome_druidpagestandard_get_background_offset (void);

guint
gnomesharp_gnome_druidpagestandard_get_background_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeDruidPageStandard, background);
}

guint gnomesharp_gnome_druidpagestandard_get_logo_background_offset (void);

guint
gnomesharp_gnome_druidpagestandard_get_logo_background_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeDruidPageStandard, logo_background);
}

guint gnomesharp_gnome_druidpagestandard_get_title_foreground_offset (void);

guint
gnomesharp_gnome_druidpagestandard_get_title_foreground_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GnomeDruidPageStandard, title_foreground);
}

void gnomesharp_entry_override_activate (GType gtype, gpointer cb);

void
gnomesharp_entry_override_activate (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeEntryClass *)klass)->activate = cb;
}

void gnomesharp_entry_base_activate (GnomeEntry* entry);

void
gnomesharp_entry_base_activate (GnomeEntry* entry)
{
	GnomeEntryClass *klass = (GnomeEntryClass *) get_threshold_class (G_OBJECT (entry));
	if (klass->activate)
		(* klass->activate) (entry);
}
void gnomesharp_fileentry_override_activate (GType gtype, gpointer cb);

void
gnomesharp_fileentry_override_activate (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeFileEntryClass *)klass)->activate = cb;
}

void gnomesharp_fileentry_base_activate (GnomeFileEntry* fentry);

void
gnomesharp_fileentry_base_activate (GnomeFileEntry* fentry)
{
	GnomeFileEntryClass *klass = (GnomeFileEntryClass *) get_threshold_class (G_OBJECT (fentry));
	if (klass->activate)
		(* klass->activate) (fentry);
}
void gnomesharp_fileentry_override_browse_clicked (GType gtype, gpointer cb);

void
gnomesharp_fileentry_override_browse_clicked (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeFileEntryClass *)klass)->browse_clicked = cb;
}

void gnomesharp_fileentry_base_browse_clicked (GnomeFileEntry* fentry);

void
gnomesharp_fileentry_base_browse_clicked (GnomeFileEntry* fentry)
{
	GnomeFileEntryClass *klass = (GnomeFileEntryClass *) get_threshold_class (G_OBJECT (fentry));
	if (klass->browse_clicked)
		(* klass->browse_clicked) (fentry);
}
void gnomesharp_fontpicker_override_font_set (GType gtype, gpointer cb);

void
gnomesharp_fontpicker_override_font_set (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeFontPickerClass *)klass)->font_set = cb;
}

void gnomesharp_fontpicker_base_font_set (GnomeFontPicker* gfp, const gchar* font_name);

void
gnomesharp_fontpicker_base_font_set (GnomeFontPicker* gfp, const gchar* font_name)
{
	GnomeFontPickerClass *klass = (GnomeFontPickerClass *) get_threshold_class (G_OBJECT (gfp));
	if (klass->font_set)
		(* klass->font_set) (gfp, font_name);
}
void gnomesharp_iconentry_override_changed (GType gtype, gpointer cb);

void
gnomesharp_iconentry_override_changed (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeIconEntryClass *)klass)->changed = cb;
}

void gnomesharp_iconentry_base_changed (GnomeIconEntry* ientry);

void
gnomesharp_iconentry_base_changed (GnomeIconEntry* ientry)
{
	GnomeIconEntryClass *klass = (GnomeIconEntryClass *) get_threshold_class (G_OBJECT (ientry));
	if (klass->changed)
		(* klass->changed) (ientry);
}
void gnomesharp_iconentry_override_browse (GType gtype, gpointer cb);

void
gnomesharp_iconentry_override_browse (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeIconEntryClass *)klass)->browse = cb;
}

void gnomesharp_iconentry_base_browse (GnomeIconEntry* ientry);

void
gnomesharp_iconentry_base_browse (GnomeIconEntry* ientry)
{
	GnomeIconEntryClass *klass = (GnomeIconEntryClass *) get_threshold_class (G_OBJECT (ientry));
	if (klass->browse)
		(* klass->browse) (ientry);
}
void gnomesharp_iconlist_override_unselect_icon (GType gtype, gpointer cb);

void
gnomesharp_iconlist_override_unselect_icon (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeIconListClass *)klass)->unselect_icon = cb;
}

void gnomesharp_iconlist_base_unselect_icon (GnomeIconList* gil, gint num, GdkEvent* evnt);

void
gnomesharp_iconlist_base_unselect_icon (GnomeIconList* gil, gint num, GdkEvent* evnt)
{
	GnomeIconListClass *klass = (GnomeIconListClass *) get_threshold_class (G_OBJECT (gil));
	if (klass->unselect_icon)
		(* klass->unselect_icon) (gil, num, evnt);
}
void gnomesharp_iconlist_override_focus_icon (GType gtype, gpointer cb);

void
gnomesharp_iconlist_override_focus_icon (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeIconListClass *)klass)->focus_icon = cb;
}

void gnomesharp_iconlist_base_focus_icon (GnomeIconList* gil, gint num);

void
gnomesharp_iconlist_base_focus_icon (GnomeIconList* gil, gint num)
{
	GnomeIconListClass *klass = (GnomeIconListClass *) get_threshold_class (G_OBJECT (gil));
	if (klass->focus_icon)
		(* klass->focus_icon) (gil, num);
}
void gnomesharp_iconlist_override_select_icon (GType gtype, gpointer cb);

void
gnomesharp_iconlist_override_select_icon (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeIconListClass *)klass)->select_icon = cb;
}

void gnomesharp_iconlist_base_select_icon (GnomeIconList* gil, gint num, GdkEvent* evnt);

void
gnomesharp_iconlist_base_select_icon (GnomeIconList* gil, gint num, GdkEvent* evnt)
{
	GnomeIconListClass *klass = (GnomeIconListClass *) get_threshold_class (G_OBJECT (gil));
	if (klass->select_icon)
		(* klass->select_icon) (gil, num, evnt);
}
void gnomesharp_iconlist_override_move_cursor (GType gtype, gpointer cb);

void
gnomesharp_iconlist_override_move_cursor (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeIconListClass *)klass)->move_cursor = cb;
}

void gnomesharp_iconlist_base_move_cursor (GnomeIconList* gil, GtkDirectionType dir, gboolean clear_selection);

void
gnomesharp_iconlist_base_move_cursor (GnomeIconList* gil, GtkDirectionType dir, gboolean clear_selection)
{
	GnomeIconListClass *klass = (GnomeIconListClass *) get_threshold_class (G_OBJECT (gil));
	if (klass->move_cursor)
		(* klass->move_cursor) (gil, dir, clear_selection);
}
void gnomesharp_iconlist_override_toggle_cursor_selection (GType gtype, gpointer cb);

void
gnomesharp_iconlist_override_toggle_cursor_selection (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeIconListClass *)klass)->toggle_cursor_selection = cb;
}

void gnomesharp_iconlist_base_toggle_cursor_selection (GnomeIconList* gil);

void
gnomesharp_iconlist_base_toggle_cursor_selection (GnomeIconList* gil)
{
	GnomeIconListClass *klass = (GnomeIconListClass *) get_threshold_class (G_OBJECT (gil));
	if (klass->toggle_cursor_selection)
		(* klass->toggle_cursor_selection) (gil);
}
void gnomesharp_iconlist_override_text_changed (GType gtype, gpointer cb);

void
gnomesharp_iconlist_override_text_changed (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeIconListClass *)klass)->text_changed = cb;
}

gboolean gnomesharp_iconlist_base_text_changed (GnomeIconList* gil, gint num, const char* new_text);

gboolean
gnomesharp_iconlist_base_text_changed (GnomeIconList* gil, gint num, const char* new_text)
{
	GnomeIconListClass *klass = (GnomeIconListClass *) get_threshold_class (G_OBJECT (gil));
	if (klass->text_changed)
		return (* klass->text_changed) (gil, num, new_text);
	return FALSE;
}
void gnomesharp_icontextitem_override_editing_started (GType gtype, gpointer cb);

void
gnomesharp_icontextitem_override_editing_started (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeIconTextItemClass *)klass)->editing_started = cb;
}

void gnomesharp_icontextitem_base_editing_started (GnomeIconTextItem* iti);

void
gnomesharp_icontextitem_base_editing_started (GnomeIconTextItem* iti)
{
	GnomeIconTextItemClass *klass = (GnomeIconTextItemClass *) get_threshold_class (G_OBJECT (iti));
	if (klass->editing_started)
		(* klass->editing_started) (iti);
}
void gnomesharp_icontextitem_override_selection_started (GType gtype, gpointer cb);

void
gnomesharp_icontextitem_override_selection_started (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeIconTextItemClass *)klass)->selection_started = cb;
}

void gnomesharp_icontextitem_base_selection_started (GnomeIconTextItem* iti);

void
gnomesharp_icontextitem_base_selection_started (GnomeIconTextItem* iti)
{
	GnomeIconTextItemClass *klass = (GnomeIconTextItemClass *) get_threshold_class (G_OBJECT (iti));
	if (klass->selection_started)
		(* klass->selection_started) (iti);
}
void gnomesharp_icontextitem_override_width_changed (GType gtype, gpointer cb);

void
gnomesharp_icontextitem_override_width_changed (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeIconTextItemClass *)klass)->width_changed = cb;
}

void gnomesharp_icontextitem_base_width_changed (GnomeIconTextItem* iti);

void
gnomesharp_icontextitem_base_width_changed (GnomeIconTextItem* iti)
{
	GnomeIconTextItemClass *klass = (GnomeIconTextItemClass *) get_threshold_class (G_OBJECT (iti));
	if (klass->width_changed)
		(* klass->width_changed) (iti);
}
void gnomesharp_icontextitem_override_editing_stopped (GType gtype, gpointer cb);

void
gnomesharp_icontextitem_override_editing_stopped (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeIconTextItemClass *)klass)->editing_stopped = cb;
}

void gnomesharp_icontextitem_base_editing_stopped (GnomeIconTextItem* iti);

void
gnomesharp_icontextitem_base_editing_stopped (GnomeIconTextItem* iti)
{
	GnomeIconTextItemClass *klass = (GnomeIconTextItemClass *) get_threshold_class (G_OBJECT (iti));
	if (klass->editing_stopped)
		(* klass->editing_stopped) (iti);
}
void gnomesharp_icontextitem_override_height_changed (GType gtype, gpointer cb);

void
gnomesharp_icontextitem_override_height_changed (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeIconTextItemClass *)klass)->height_changed = cb;
}

void gnomesharp_icontextitem_base_height_changed (GnomeIconTextItem* iti);

void
gnomesharp_icontextitem_base_height_changed (GnomeIconTextItem* iti)
{
	GnomeIconTextItemClass *klass = (GnomeIconTextItemClass *) get_threshold_class (G_OBJECT (iti));
	if (klass->height_changed)
		(* klass->height_changed) (iti);
}
void gnomesharp_icontextitem_override_selection_stopped (GType gtype, gpointer cb);

void
gnomesharp_icontextitem_override_selection_stopped (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeIconTextItemClass *)klass)->selection_stopped = cb;
}

void gnomesharp_icontextitem_base_selection_stopped (GnomeIconTextItem* iti);

void
gnomesharp_icontextitem_base_selection_stopped (GnomeIconTextItem* iti)
{
	GnomeIconTextItemClass *klass = (GnomeIconTextItemClass *) get_threshold_class (G_OBJECT (iti));
	if (klass->selection_stopped)
		(* klass->selection_stopped) (iti);
}
void gnomesharp_icontextitem_override_text_changed (GType gtype, gpointer cb);

void
gnomesharp_icontextitem_override_text_changed (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GnomeIconTextItemClass *)klass)->text_changed = cb;
}

gboolean gnomesharp_icontextitem_base_text_changed (GnomeIconTextItem* iti);

gboolean
gnomesharp_icontextitem_base_text_changed (GnomeIconTextItem* iti)
{
	GnomeIconTextItemClass *klass = (GnomeIconTextItemClass *) get_threshold_class (G_OBJECT (iti));
	if (klass->text_changed)
		return (* klass->text_changed) (iti);
	return FALSE;
}
